name: docker-swarm-ssh-deploy
author: kamina
description: A GitHub Action that enables you to publish your app as a Docker stack to a remote Docker swarm.
inputs:
  remote_host:
    description: Docker host to connect to
    required: true
  input_ssh_key:
    description: SSH key for the server
    required: true
runs:
  using: docker
  image: Dockerfile
branding:
  icon: droplet
  color: blue
